[2023-05-23T19:35:30.576+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T19:35:30.583+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T19:35:30.584+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T19:35:30.585+0000] {taskinstance.py:1363} INFO - Starting attempt 9 of 9
[2023-05-23T19:35:30.586+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T19:35:30.595+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2019-04-01 00:00:00+00:00
[2023-05-23T19:35:30.600+0000] {standard_task_runner.py:55} INFO - Started process 15418 to run task
[2023-05-23T19:35:30.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'load', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmp0h8d2k95']
[2023-05-23T19:35:30.607+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask load
[2023-05-23T19:35:30.619+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T19:35:30.662+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T19:35:30.734+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=9
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-05-23T19:35:30.777+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 86, in load
    cursor.execute(copy_sql)
psycopg2.errors.UndefinedFile: could not open file "/tmp/{exec_date}_new.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2023-05-23T19:35:30.794+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=load, execution_date=20190401T000000, start_date=20230523T193530, end_date=20230523T193530
[2023-05-23T19:35:30.803+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 56 for task load (could not open file "/tmp/{exec_date}_new.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 15418)
[2023-05-23T19:35:30.862+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T19:35:30.880+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
