[2023-05-23T17:23:45.191+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T17:23:45.197+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T17:23:45.198+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T17:23:45.198+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-23T17:23:45.198+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T17:23:45.205+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2019-04-01 00:00:00+00:00
[2023-05-23T17:23:45.211+0000] {standard_task_runner.py:55} INFO - Started process 14149 to run task
[2023-05-23T17:23:45.214+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'load', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpwcdpm8rz']
[2023-05-23T17:23:45.217+0000] {standard_task_runner.py:83} INFO - Job 49: Subtask load
[2023-05-23T17:23:45.228+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T17:23:45.267+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T17:23:45.312+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-05-23T17:23:45.313+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 50, in load
    conn = psycopg2.connect(host='localhost', database='airflow', user='airflow', password='airflow', port='5432')
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-05-23T17:23:45.322+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=load, execution_date=20190401T000000, start_date=20230523T172345, end_date=20230523T172345
[2023-05-23T17:23:45.329+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 49 for task load (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 14149)
[2023-05-23T17:23:45.346+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T17:23:45.359+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-26T12:13:07.619+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-26T12:13:07.624+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-26T12:13:07.625+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-26T12:13:07.625+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-26T12:13:07.626+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-26T12:13:07.633+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2019-04-01 00:00:00+00:00
[2023-05-26T12:13:07.639+0000] {standard_task_runner.py:55} INFO - Started process 604 to run task
[2023-05-26T12:13:07.642+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'load', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmplq10i4q9']
[2023-05-26T12:13:07.645+0000] {standard_task_runner.py:83} INFO - Job 251: Subtask load
[2023-05-26T12:13:07.656+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-26T12:13:07.698+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.load scheduled__2019-04-01T00:00:00+00:00 [running]> on host b55299475a02
[2023-05-26T12:13:07.751+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-05-26T12:13:07.764+0000] {base.py:71} INFO - Using connection ID 'postgresql_conn' for task execution.
[2023-05-26T12:13:07.766+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-26T12:13:07.872+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-26T12:13:07.882+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=algolia_test, task_id=load, execution_date=20190401T000000, start_date=20230526T121307, end_date=20230526T121307
[2023-05-26T12:13:07.935+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-05-26T12:13:07.960+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
