[2023-05-23T22:16:04.671+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-02T00:00:00+00:00 [queued]>
[2023-05-23T22:16:04.678+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-02T00:00:00+00:00 [queued]>
[2023-05-23T22:16:04.678+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T22:16:04.678+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-23T22:16:04.679+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T22:16:04.686+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2019-04-02 00:00:00+00:00
[2023-05-23T22:16:04.691+0000] {standard_task_runner.py:55} INFO - Started process 677 to run task
[2023-05-23T22:16:04.695+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'load', 'scheduled__2019-04-02T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpazsag600']
[2023-05-23T22:16:04.697+0000] {standard_task_runner.py:83} INFO - Job 103: Subtask load
[2023-05-23T22:16:04.711+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T22:16:04.753+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.load scheduled__2019-04-02T00:00:00+00:00 [running]> on host 7bd2786c5ce5
[2023-05-23T22:16:04.801+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T00:00:00+00:00
[2023-05-23T22:16:04.803+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-23T22:16:04.813+0000] {logging_mixin.py:137} INFO - Index(['Unnamed: 0', 'id', 'shop_domain', 'application_id',
       'autocomplete_enabled', 'user_created_at_least_one_qr',
       'nbr_merchandised_queries', 'nbrs_pinned_items', 'showing_logo',
       'has_changed_sort_orders', 'analytics_enabled', 'use_metafields',
       'nbr_metafields', 'use_default_colors', 'show_products',
       'instant_search_enabled', 'instant_search_enabled_on_collection',
       'only_using_faceting_on_collection', 'use_merchandising_for_collection',
       'index_prefix', 'indexing_paused', 'install_channel', 'export_date',
       'has_specific_prefix'],
      dtype='object')
[2023-05-23T22:16:04.825+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 56, in load
    df.to_sql('algolia_tests', engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 2882, in to_sql
    method=method,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 728, in to_sql
    **engine_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1758, in to_sql
    dtype=dtype,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 1650, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/sql.py", line 858, in create
    raise ValueError(f"Table '{self.name}' already exists.")
ValueError: Table 'algolia_tests' already exists.
[2023-05-23T22:16:04.836+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=load, execution_date=20190402T000000, start_date=20230523T221604, end_date=20230523T221604
[2023-05-23T22:16:04.842+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 103 for task load (Table 'algolia_tests' already exists.; 677)
[2023-05-23T22:16:04.867+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T22:16:04.879+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-26T12:13:13.310+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-02T00:00:00+00:00 [queued]>
[2023-05-26T12:13:13.316+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.load scheduled__2019-04-02T00:00:00+00:00 [queued]>
[2023-05-26T12:13:13.317+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-26T12:13:13.317+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-05-26T12:13:13.317+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-26T12:13:13.324+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2019-04-02 00:00:00+00:00
[2023-05-26T12:13:13.329+0000] {standard_task_runner.py:55} INFO - Started process 607 to run task
[2023-05-26T12:13:13.333+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'load', 'scheduled__2019-04-02T00:00:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpb3h5lm_v']
[2023-05-26T12:13:13.335+0000] {standard_task_runner.py:83} INFO - Job 252: Subtask load
[2023-05-26T12:13:13.348+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-26T12:13:13.390+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.load scheduled__2019-04-02T00:00:00+00:00 [running]> on host b55299475a02
[2023-05-26T12:13:13.438+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=load
AIRFLOW_CTX_EXECUTION_DATE=2019-04-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-02T00:00:00+00:00
[2023-05-26T12:13:13.446+0000] {base.py:71} INFO - Using connection ID 'postgresql_conn' for task execution.
[2023-05-26T12:13:13.447+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-26T12:13:13.530+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-05-26T12:13:13.539+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=algolia_test, task_id=load, execution_date=20190402T000000, start_date=20230526T121313, end_date=20230526T121313
[2023-05-26T12:13:13.584+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2023-05-26T12:13:13.600+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
