[2023-05-23T13:57:50.249+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.transform scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T13:57:50.255+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.transform scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T13:57:50.255+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:57:50.256+0000] {taskinstance.py:1363} INFO - Starting attempt 10 of 10
[2023-05-23T13:57:50.256+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:57:50.263+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2019-04-01 00:00:00+00:00
[2023-05-23T13:57:50.268+0000] {standard_task_runner.py:55} INFO - Started process 5928 to run task
[2023-05-23T13:57:50.272+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'transform', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpqggys488']
[2023-05-23T13:57:50.274+0000] {standard_task_runner.py:83} INFO - Job 43: Subtask transform
[2023-05-23T13:57:50.285+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T13:57:50.322+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.transform scheduled__2019-04-01T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T13:57:50.366+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-05-23T13:57:50.368+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-23T13:57:50.385+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 45, in transform
    print(filter_data[['application_id', 'index_prefix', 'has_specific_prefix']].head())
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3464, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['has_specific_prefix'] not in index"
[2023-05-23T13:57:50.396+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=transform, execution_date=20190401T000000, start_date=20230523T135750, end_date=20230523T135750
[2023-05-23T13:57:50.402+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 43 for task transform ("['has_specific_prefix'] not in index"; 5928)
[2023-05-23T13:57:50.443+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T13:57:50.457+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
