[2023-05-23T13:59:39.089+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.transform scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T13:59:39.095+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: algolia_test.transform scheduled__2019-04-01T00:00:00+00:00 [queued]>
[2023-05-23T13:59:39.095+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:59:39.095+0000] {taskinstance.py:1363} INFO - Starting attempt 12 of 12
[2023-05-23T13:59:39.096+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-05-23T13:59:39.103+0000] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): transform> on 2019-04-01 00:00:00+00:00
[2023-05-23T13:59:39.108+0000] {standard_task_runner.py:55} INFO - Started process 6023 to run task
[2023-05-23T13:59:39.112+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'algolia_test', 'transform', 'scheduled__2019-04-01T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/algolia-dag.py', '--cfg-path', '/tmp/tmpweoryzk3']
[2023-05-23T13:59:39.114+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask transform
[2023-05-23T13:59:39.125+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-05-23T13:59:39.162+0000] {task_command.py:376} INFO - Running <TaskInstance: algolia_test.transform scheduled__2019-04-01T00:00:00+00:00 [running]> on host c3034470bbd8
[2023-05-23T13:59:39.206+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=algolia_test
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2019-04-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=12
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-04-01T00:00:00+00:00
[2023-05-23T13:59:39.208+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-05-23T13:59:39.223+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 302, in na_logical_op
    result = op(x, y)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/roperator.py", line 52, in rand_
    return operator.and_(right, left)
TypeError: unsupported operand type(s) for &: 'str' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 316, in na_logical_op
    result = libops.scalar_binop(x, y, op)
  File "pandas/_libs/ops.pyx", line 210, in pandas._libs.ops.scalar_binop
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/roperator.py", line 52, in rand_
    return operator.and_(right, left)
TypeError: unsupported operand type(s) for &: 'bool' and 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/algolia-dag.py", line 43, in transform
    filter_data = trim_data[trim_data.application_id.notnull() & trim_data.application_id != '' & trim_data.application_id]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/arraylike.py", line 66, in __rand__
    return self._logical_method(other, roperator.rand_)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/series.py", line 5513, in _logical_method
    res_values = ops.logical_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 392, in logical_op
    res_values = na_logical_op(lvalues, rvalues, op)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 328, in na_logical_op
    ) from err
TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]
[2023-05-23T13:59:39.233+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=algolia_test, task_id=transform, execution_date=20190401T000000, start_date=20230523T135939, end_date=20230523T135939
[2023-05-23T13:59:39.240+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task transform (Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]; 6023)
[2023-05-23T13:59:39.283+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-05-23T13:59:39.299+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
